### ISSUE TITLE
In Person Appts (Past, Upcoming Confirmed & Cancelled) - Handling when there is no facility name, address, & or  phone

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7268]
## Description 
As the VA, I want to to handle consistency what happens when there is no facility name, facility address, or facility phone in In-Person VA Appointments, so that its easier for the Veterans to understand 

## Acceptance Criteria
  

**Scenario 1 : When no facility address or facility phone number w/ direction link** 

- [ ]  [Facility name] (no change)
- [ ] Text: We can't show your health care facility's address or phone number right now. But you can still get directions to the facility. You can also find your facility's information on VA.gov.
- [ ] [link] Get directions 
- [ ] [link] Go to VA.gov to find your VA facility (goes to: https://www.va.gov/find-locations/)

**Scenario 2: When no facility address w/ direction link** 
- [ ]  [Facility name] (no change)
 - [ ] Text: We can't show your health care facility's address right now. But you can still get directions to the facility. You can also call your facility to get the address.
- [ ] [link] Get directions
- [ ] [Facility phone #] (no change)
-  [ ] TTY: 711 (no change)
 

**Scenario 3: When no facility name, facility address or facility phone number w/ direction link** 
- [ ] Text: We can't show your health care facility's information right now. But you can still get directions to the facility. You can also find your facility's information on VA.gov.
- [ ] [link] Get directions 
- [ ] [link] Go to VA.gov to find your VA facility (goes to: https://www.va.gov/find-locations/)

**Scenario 4 : When no facility address or facility phone number w/ NO direction link** 

- [ ]  [Facility name] (no change)
- [ ] Text: We can't show your health care facility's address or phone number right now. Try again later. Or go to VA.gov (goes to https://www.va.gov) to find your facility's information.
- [ ] [link] Go to VA.gov to find your VA facility (goes to: https://www.va.gov/find-locations/)

**Scenario 5 : When no facility address w/ NO direction link** 
- [ ]  [Facility name] (no change)
- [ ] Text: We can't show your health care facility's address right now. Try again later. Or call your facility to get the address.
- [ ] [Facility phone #] (no change)
-  [ ] TTY: 711 (no change)
 

**Scenario 6:  When no facility name, facility address or facility phone number w/ NO direction link** 
- [ ] Text: We can't show the health care facility's information right now. Try again later. Or go to VA.gov (goes to https://www.va.gov) to find your facility's information.
[link] Go to VA.gov to find your VA facility (goes to: https://www.va.gov/find-locations/)

## Documentation 

- [Get: /v0/appointments](https://department-of-veterans-affairs.github.io/va-mobile-app/api/#/paths/~1v0~1appointments/get)
- Figma File for Reference -  [Appt List - In Person Appt - Card Design Update](https://www.figma.com/file/ZIHY63cFlD7pFjqQLA5rFN/%F0%9F%94%8D-Appointments-2.0---Working---VAMobile?type=design&node-id=2245-4711&mode=design&t=5IOV03gfsWL9K5xV-0)

## Accessibility Requirements
- [ ] Screen reader accessible 

## Notes & Open Questions
- VA appointments only - no changes to community care appointments
-  For when there's no facility name/address/phone, all other fields should stay in the same place. This is still just going to appear after clinic location and before the details you shared fields. 
- These edge cases for empty states are just showing fields affected. All other fields should be handled as normal. Per FE, even if we don't have the address, we could still show the directions link because we get the latitude/longitude from another place. These edge cases show what the error copy should be if we can show the directions link and if we can't (that field is also not working). If phone number is unavailable, we should omit TTY."		
- Engineering may need decide to hide fields to make this work -UX / Product support 

- Dependencies/Roadblocks: No
- Any internal/external dependencies? No 
- Test accounts needed? Yes, one with in person appts
- Does this require QA? Yes - comparison of old vs new 
    
- Dev Notes: 

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHpoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4955c9867a46dc6ad221f9a6d95ae490b558af26/Screenshot%202023-11-16%20at%2012.43.30%20PM.png)

**Comment by mistymg** [comment]
@bischoffa Just looking at pending tickets for Appointments before handoff. Can you explain what this means?

**Comment by bischoffa** [comment]
I think that comment was from our discussions. Regarding the how FE wants to enable this and make it work.  

I mocked these up today and was going to re-review them tomorrow (cleaner brain) then reach out to see if you could give feedback.

**Comment by mistymg** [comment]
Ahh gotchya! Now I know what you mean :)

**Comment by mistymg** [comment]
Adding a note for Eng: These scenarios are what is shown for null facility name/address/phone for upcoming (confirmed) appts. When these fields are null for past and canceled appts, we should show the copy version with no direction link. I can speak more about this in handoff on Thursday.

**Comment by mistymg** [comment]
Updated screenshot of spreadsheet in ticket.

**Comment by DJUltraTom** [comment]
test cases are here: https://dsvavsp.testrail.io/index.php?/suites/view/92&group_by=cases:section_id&group_id=12986&group_order=asc&display_deleted_cases=0

**Comment by rbontrager** [comment]
Couple issues have been found while going through the test cases. 
- Showing the get directions link for cancelled/past appts
- Scenario 3 (the one without the facility header) text is all in bold. There is also a bigger amount of space between the provider name and the scenario 3 text than normal (like the code expects a non-existent header there).

**Comment by Sparowhawk** [comment]
fixed the directions link for past/cancelled appts

from what I show scenario 3 is correct. Here is a screenshot of that scenario. Text isn't bolded and the spacing follows WCAG 2.2

<img width="425" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUw5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a27a63b83863747954a975b447dd027014288baa/Screenshot%202024-01-25%20at%2010.36.25%20AM.png" alt="Screenshot 2024-01-25 at 10.36.25 AM.png" />

**Comment by rbontrager** [comment]
I'm still seeing scenario 3 in bold on my end.  Talking to Dylan and trying to figure out what could be the difference.

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWtCQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c78f930f25f78fcb91e43fb011ab8c70a79009c3/8EE7C317-BDF2-4987-BE24-AC29A63FD095.png" alt="8EE7C317-BDF2-4987-BE24-AC29A63FD095.png" />

**Comment by DJUltraTom** [comment]
yes! successfully completed test run with all the test cases,
[Test run here](https://dsvavsp.testrail.io/index.php?/runs/view/5111&group_by=cases:section_id&group_order=asc)
QA approves this change!

**Comment by DJUltraTom** [comment]
spot checked appointments with judy.morrison and things appear as expected
