### ISSUE TITLE
Migrate appointmentsSlice to React Query

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#7744]

**Comment by rbontrager** [comment]
@Sparowhawk Issues found:
1.  Appointments not showing as canceled after canceling.  This looks to be a refresh issue.
2.  Past appointments aren't displaying in the list properly.  Examples in judy:
   -  if you select oct 2023-dec 2023 and navigate through the pages you have an appts for november 2023, then december 2023, then november 2023 again, then october 2023, then november 2023 again, then october 2023 again.
   -  If you select 'all of 2024' it isn't sorting the appointments for newest to oldest
   -  I'm also occasionally seeing dates for outside the period

**Comment by rbontrager** [comment]
@Sparowhawk I've found a couple more issues dealing with error cases/pagination/some more past appt issues.

1. Using charles I was able to block the appointments api call and get the error screen with the 'refresh screen' button.  If I unblock the appointments api call and hit 'refresh screen' it does nothing.  Usually it will try to refetch the api call at this point and reshow the list.
2. Appointments correctly goes to the top of the page as you click the pages of appointments the first time.  It doesn't go to the top the 2nd through the pages though.
3. Nov 2023 - Jan 2024 doesn't display january dates in past appointments (they are showing up when you select all of 2024)

**Comment by Sparowhawk** [comment]
fixed in https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7744

**Comment by rbontrager** [comment]
@Sparowhawk 
- Number 4 is not fixed all the way. For past appointments you should still have the 'select a date range' picker for any option when you don't have appointments.  
- This only happens the FIRST time upon opening past appts. If you navigate to past appointments > click on select a date range > select any date range you will notice that the list hasn't refreshed and its still the 'past 3 months' list of appts.  
- Revert previous past appointment date logic (I finally see what is happening and it was fine previously).

**Comment by Sparowhawk** [comment]
fixed 1

**Comment by Sparowhawk** [comment]
fixed 2

**Comment by rbontrager** [comment]
Testrail case passed and is run here: [Appointments RQ Test](https://dsvavsp.testrail.io/index.php?/runs/view/5371&group_by=cases:section_id&group_order=asc).  Approved by QA.
