### ISSUE TITLE
Componentization - VA in person appointments - Detail View

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va-mobile-app#8501]
## Description 
As an engineer, I want create and reuse different standardized components for appointments, so that it will easier for other teams to start working in appointments and the different appointment types can be more aligned.

Specific details of the components needed can be found in [this spreadsheet ](https://docs.google.com/spreadsheets/d/1Q_kdxH1zJjmJ0xF5XC7aMUVzlwxtO3wAEvYxFrTACsc/edit#gid=402791918) (see columns C, D, E on "Details screen section" tab and also "VA In Person - Details" tab as needed) and the design specs can be found in [Figma](https://www.figma.com/file/ZIHY63cFlD7pFjqQLA5rFN/%F0%9F%94%8D-Appointments-2.0---Working---VAMobile?type=design&node-id=2605-9728&mode=design&t=vC9P2gjQDJtM6fsE-4)

As part of this story we want to: 
- Create new components that are needed for confirmed, past, and canceled VA in-person appointment
- Plug in any pre-existing components
- Update end to end tests
- Update headings to match [Figma](https://www.figma.com/file/ZIHY63cFlD7pFjqQLA5rFN/%F0%9F%94%8D-Appointments-2.0---Working---VAMobile?type=design&node-id=2605-9728&mode=design&t=vC9P2gjQDJtM6fsE-4) file
- VQA with content/design

## Acceptance Criteria

-  [ ] New components have been created
-  [ ] Existing components have been brought in
-  [ ] E2E tests have been updated
-  [ ] VQA by content
-  [ ] VQA by design

**Comment by mistymg** [comment]
Just a note this ticket doesn't include pending appointments. That will be it's own separate ticket.

**Comment by Sparowhawk** [comment]
fixed number 3

**Comment by Sparowhawk** [comment]
fixed number 1

**Comment by rbontrager** [comment]
@Sparowhawk With Misty's clarification on what past pending and past canceled appts should look like it looks like we have one tiny bug.  I'm still seeing the 'cancel request' button for past pending appts.  It was removed in older versions of the app and any cancel requests are removed for past upcoming appts.

**Comment by Sparowhawk** [comment]
removed the cancel request button

**Comment by wavelaurenrussell** [comment]
Let's adjust the spacing between sections so that we'll know what content goes together. Like: 

**Details**
Detail 1
Detail 2

--not--

**Details**

Detail 1

Detail 2

**Comment by Sparowhawk** [comment]
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOW5xQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--04464a124dfafb51fd74b3ccf58d00cf944d446a/Screen%20Recording%202024-05-16%20at%202.27.29%E2%80%AFPM.mov)

**Comment by Sparowhawk** [comment]
fixed

**Comment by rbontrager** [comment]
Verified that VA in person appointments match the spreadsheet and the figma design.  Approved by QA.
