### ISSUE TITLE
Update logs and emblems global implementation

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#9632]
### Monthly Update for Stakeholders

 
|Date|  Progress & Key Accomplishments| Issues/Risks/Blockers|
|-------| --------|---------|
|9/9/24| Not started
|9/17/24| Engineering in progress

### What was updated in the Design System?
In **va-mobile-library**, the official VA logos and emblems were updated in version 0.6.0 of the [Assets package](https://github.com/department-of-veterans-affairs/va-mobile-library/tree/main/packages/assets) and [Figma library](https://www.figma.com/design/X8gXRl1MaRAE7lKcwgr5Rj/%F0%9F%93%90-Icon-Library---Design-System---VA-Mobile?node-id=212-1739) to be consistent with VA.gov. The new files are:
- [VALogo](https://github.com/department-of-veterans-affairs/va-mobile-library/tree/main/packages/assets/VALogo)
     - VAOnDark.png
     - VAOnLight.png
- [serviceEmblems](https://github.com/department-of-veterans-affairs/va-mobile-library/tree/main/packages/assets/serviceEmblems)
     - vic-air-force-coat-of-arms.png
     - vic-army-symbol.png
     - vic-cg-emblem.png
     - vic-navy-emblem.png
     - vic-space-force-logo-on-dark.png
     - vic-space-force-logo-on-light.png
     - vic-space-force-logo.png
     - vic-usmc-emblem.png

### What changes are recommended in the Flagship Mobile App?
1. In **va-mobile-app**, the VA logos and emblems in the [VAIcon component](https://github.com/department-of-veterans-affairs/va-mobile-app/tree/develop/VAMobile/src/components/VAIcon) should be updated as follows. After the files are updated, the [vaParentLogo](https://github.com/department-of-veterans-affairs/va-mobile-app/tree/develop/VAMobile/src/components/VAIcon/svgs/vaParentLogo) and [dodBranch](https://github.com/department-of-veterans-affairs/va-mobile-app/tree/develop/VAMobile/src/components/VAIcon/svgs/dodBranch) files should be removed from the VAIcon component.
     - **Update**: Logo.svg :arrow_right: VAOnDark.png
     - **Update**: AirForce.svg :arrow_right: vic-air-force-coat-of-arms.png
     - **Update**: Army.svg :arrow_right: vic-army-symbol.png
     - **Update**: CoastGuard.svg :arrow_right: vic-cg-emblem.png
     - **Update**: MarineCorps.svg :arrow_right: vic-usmc-emblem.png
     - **Update**: Navy.svg :arrow_right: vic-navy-emblem.png
     - **New**: VAOnLight.png
     - **New**: vic-space-force-logo-on-dark.png
     - **New**:  vic-space-force-logo-on-light.png
     - **New**: vic-space-force-logo.png
2. In **Figma**, the VA logos and emblems should be updated in the shipped files. After the files are updated, the Logo component should be removed from the Flagship Library file.

### Where are these files used in the Flagship Mobile App?
Currently, the logos and service emblems are used on the home screen, profile screen, and Veteran Status.

## Additional resources
- [How to use the Assets package](https://department-of-veterans-affairs.github.io/va-mobile-app/design/About/For%20engineers/assets)
- Documentation on Logos will be available in the coming weeks
- For more information about Service Emblems, reach out to #va-mobile-design-system in Slack.

## Acceptance criteria
- [ ] Logos and emblems are updated in va-mobile-app with the files in va-mobile-library's Assets package
- [ ] Logos and emblems are removed from VAIcon component in va-mobile-app
- [ ] After the above two bullets are completed, pass this ticket to Brea for the remainder of ACs
- [ ] Logos and emblems are updated in shipped files in Figma.
- [ ] Logos and emblems are removed from the Flagship Library file in Figma.

**Comment by TKDickson** [comment]
@theodur can you associate your PR with this ticket, instead of the epic itself? I will need to move my test plan over here as well, note to self

**Comment by TKDickson** [comment]
VA icons show appropriately, light and dark mode, on:
- [ ] Initial app load
- [ ] Pre-login screen
- [ ] Log in sync screen
- [ ] Log out sync screen
- [ ] Onboarding carousel

Military branch icons show appropriately, light and dark mode, on:
- [ ] Home (nametag component)
- [ ] Profile (nametag component)
- [ ] Veteran status card
- [ ] Military history screen....? maybe? Or we may have removed that UI. I'll check there either way.

Also:
- [ ] Can still log into demo mode by multiple taps on the prelogin screen, without assistive tech
- [ ] Can still log into demo mode by multiple taps on the prelogin screen, *with* assistive tech
- [ ] Screenreader announcement of VA icon on home is unchanged & correct
Screenreader announcement of each military branch icon is unchanged and correct:

- [ ] Air force
- [ ] coast guard
- [ ] army
- [ ] Navy
- [ ] Space force
- [ ] Marines

**Comment by TKDickson** [comment]
@theodur on the veteran status screen (which doesn't have light and dark mode variations), previously we were always showing the (equivalent of the) vic-space-force-logo-on-dark.png logo, so the "USSF" text would have sufficient contrast.

On this branch/with this change, the space force logo on the veteran status screen is changing with dark/light mode, which is causing this contrast issue (green circle mine/added): <img width="858" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXdMQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--af4c2076ce26fa8253c15bd5684d61e21e9ff645/image.png" alt="image.png" />



Can we go back to having an override, but with sufficient contrast, even with the DS changes?

**Comment by TKDickson** [comment]
And if all this ^ is actually something to chat about with the design system team, let me know!

**Comment by theodur** [comment]
@TKDickson Good catch, that was because the new `MilitaryBranchEmblem` component defaulted to setting it based on the theme. I added an override option to it, so this should be fixed now

**Comment by TKDickson** [comment]
[Space Force emblem now displaying with enough contrast, light and dark mode, regardless of screen. ](https://drive.google.com/file/d/1BJau8Lcki6ZthCJ9mgx8zbsDDemc6vQ2/view?usp=sharing)

**Comment by TKDickson** [comment]
Running [iOS](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/11111364637) and [Android](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/11111362382) scripts (something appears to have gone awry with the PR, because they're not running there automatically)

**Comment by TKDickson** [comment]
@theodur looks like you need to make changes to the VeteranStatus detox script? [Failing on emblems checks](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/11111362382/job/30871168058)

**Comment by theodur** [comment]
Dang it, thought I got them all. Should be fixed now @TKDickson. 
I'll wait and see if the PR decides to automatically kick off the E2E tests. If not, I'll manually run them

**Comment by theodur** [comment]
No dice, had to run them manually:
- [iOS](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/11112783439)
- [Android](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/11112774696)

**Comment by TKDickson** [comment]
Sadly, the VeteranStatusCard e2e script is also still failing due to logo/emblem change.

**Comment by theodur** [comment]
Fixed it and kicked off new test runs

https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/11129832012

https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/11129848124
